apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-config
  namespace: ingress-nginx
data:
  proxy-buffer-size: "128k"
  proxy-body-size: "50m"
  client-header-buffer-size: "64k"
  large-client-header-buffers: "4 128k"
  