apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base resources
bases:
  - ../../base

# Apply environment-specific patches (like replica count, resource limits, etc.)
patchesStrategicMerge:
  - patches.yaml

# You can also override environment-specific settings in ConfigMaps or Secrets
configMapGenerator:
  - name: keycloak-env-config
    literals:
      - KEYCLOAK_LOG_LEVEL=debug
      - KEYCLOAK_FRONTEND_URL=https://dev-keycloak.jameszmapepa.io

secretGenerator:
  - name: keycloak-db-secret
    literals:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password

# Add a namespace (if it's different across environments)
namespace: keycloak-dev

# Name prefixes (optional) to differentiate resources across environments
namePrefix: dev-
