apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mysql-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/keycloak/mysql