apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Assumes you have cert-manager set up
spec:
  tls:
  - hosts:
    - keycloak-dev.seamlessremit.com
    secretName: keycloak-tls-secret
  rules:
  - host: keycloak-dev.seamlessremit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak  # Replace with your actual Keycloak service name
            port: 
              number: 8080  # Replace with your actual Keycloak service port